version: 1
groups:
  forecastEvalReport:
    paths:
      - R/
      - inst/
      - man/
      - data-raw/
      - DESCRIPTION
      - NAMESPACE
      - NEWS.md
    rules:
      - preset: r-package
      - preset: r-news-titled
