#' @keywords internal
"_PACKAGE"

#' @importFrom stats as.formula median setNames
#' @importFrom grDevices colorRampPalette
#' @importFrom utils str
NULL

# Column names used via non-standard evaluation (dplyr/plotly formulas)
utils::globalVariables(c(
  "Observed",
  "WIS_Season",
  "ae_median",
  "allowed_population",
  "borderEnd",
  "borderStart",
  "forecastValue",
  "hi50",
  "hi95",
  "horizon",
  "horizonEnd",
  "horizonName",
  "horizonReachesPeak",
  "horizonStart",
  "in50",
  "in95",
  "is_no_eval",
  "is_stable",
  "is_transmission",
  "lo50",
  "lo95",
  "location",
  "median_agreement",
  "median_pct_error",
  "median_raw_error",
  "median_value",
  "observedAtPredictedPeak",
  "observedPeakDate",
  "observedPeakValue",
  "observed_count",
  "output_type_id",
  "pct_error",
  "peakNote",
  "peakWeekAccuracy",
  "peakWeekForecastExists",
  "peakWeekForecastValue",
  "peakWeekMagnitudeOff",
  "peakWeekNote",
  "peakWeekReachedInTesting",
  "per_agreement",
  "predictedPeakAccuracy",
  "predictedPeakDate",
  "predictedPeakMagnitudeOff",
  "predictedPeakNote",
  "predictedPeakTimingLabel",
  "predictedPeakTimingOff",
  "predictedPeakValue",
  "raw_error",
  "reference_date",
  "sameDayAccuracy",
  "sameDayMagnitudeOff",
  "season",
  "shade_shapes",
  "targetValue",
  "target_end_date",
  "value",
  "wis",
  "wis_ok"
))
